// AUTO-GENERATED by sim/oracle_train.py --dump-tu — DO NOT EDIT.
// M7.2 train_unit golden: fwd=int8 seed=3 k=2 lr_shift=4 wshift=2 xshift=2 backward=int8 dshift=2
`define TU_NSAMP   64
`define TU_STRIDE  70
`define TU_K       2
`define TU_LR      4
`define TU_O_X 0
`define TU_O_T 4
`define TU_O_Z1 8
`define TU_O_H 12
`define TU_O_Z2 16
`define TU_O_Y 20
`define TU_O_ERR 24
`define TU_O_SSE 28
`define TU_O_D2 29
`define TU_O_W2TD2 33
`define TU_O_D1 37
`define TU_O_DW2 41
`define TU_O_DW1 45
`define TU_O_W1A 53
`define TU_O_B1A 61
`define TU_O_W2A 65
`define TU_O_B2A 69
