#!/usr/bin/env python3
"""Build a single-frame ICAP write sequence for the LUT-INIT surgery (task #8).

INVESTIGATION ARTIFACT (task #8 part 1) -- see docs/icap_investigation.md. The proven
live LUT edit uses PCAP/loadbp (docs/lut_surgery.md); this builds the sequence that the
ICAP-from-inside attempts streamed. The frame location is prjxray-validated and the
extraction is correct; the wall was the Zynq-7 ICAP config handshake, not this sequence.


Extracts the one configuration frame that holds l0's LUT (frame 0x0040149B, per
prjxray: tile CLBLM_R_X17Y21 baseaddr 0x00401480 + INIT segbit frame-offset 27),
plus its neighbour 0x0040149C as a safe pad (single-frame writes push one extra
frame through the config pipeline). Wraps them in a minimal 7-series ICAP write
command sequence (CRC disabled) and emits a C array the NEORV32 firmware streams
to the XBUS->ICAPE2 port, rewriting that frame -- and thus the LUT truth table --
from inside the fabric.

  icap-build-frame.py <source_partial.bit> <out.h>
The source should be the *patched* (Y=0x5B) partial so the written frame flips
l0's INIT[1]; frame index 63 in the first FDRI block is prjxray+diff validated.
"""
import struct, sys

SYNC = b'\xaa\x99\x55\x66'
IDCODE = 0x03722093              # xc7z010
FAR_TARGET = 0x0040149B          # frame holding l0 (prjxray CLBLM_R_X17Y21 + segbit)
FRAME_WORDS = 101
FAR_BLOCK = 0x00401400           # column-start FAR of the FDRI block holding the frame
FRAME_INDEX = 63                 # 0x0040149B = FAR_BLOCK col(36) + 0x00401480 col minor 27


def config_words(path):
    b = open(path, 'rb').read()
    s = b.find(SYNC)
    n = (len(b) - s) // 4
    return list(struct.unpack('>%dI' % n, b[s:s + n * 4]))


def fdri_data_start_after_far(words, target_far):
    # walk packets, tracking FAR; return the data start of the FDRI block whose
    # preceding FAR == target_far (the first such block).
    i = 0
    cur_far = None
    while i < len(words):
        w = words[i]
        if (w >> 29) == 1:
            op = (w >> 27) & 3
            addr = (w >> 13) & 0x3fff
            cnt = w & 0x7ff
            if addr == 1 and op == 2 and cnt >= 1:     # FAR write
                cur_far = words[i + 1]
            if addr == 2 and op == 2:                  # FDRI; type2 data follows
                if cur_far == target_far:
                    return i + 2
            i += 1 + (cnt if op == 2 else 0)
        elif (w >> 29) == 2:
            i += 1 + (w & 0x7ffffff)
        else:
            i += 1
    raise RuntimeError(f"no FDRI block after FAR 0x{target_far:08x}")


def main():
    src, out = sys.argv[1], sys.argv[2]
    w = config_words(src)
    base = fdri_data_start_after_far(w, FAR_BLOCK)
    start = base + FRAME_INDEX * FRAME_WORDS
    frames2 = w[start:start + 2 * FRAME_WORDS]   # target frame + neighbour (pad)
    assert len(frames2) == 2 * FRAME_WORDS, "frame extraction out of range"

    # ICAP write command sequence (CRC disabled), mirroring the working partial's
    # header + finalization (GRESTORE/START activate the written frame).
    seq = [0xFFFFFFFF] * 16 + [          # long dummy flush so the engine syncs
        0xAA995566,                       # sync
        0x20000000,                       # NOP
        0x30008001, 0x00000007,           # CMD = RCRC
        0x20000000, 0x20000000,           # NOP x2
        0x30018001, IDCODE,               # write IDCODE
        0x30008001, 0x00000001,           # CMD = WCFG
        0x20000000,                       # NOP
        0x30002001, FAR_TARGET,           # FAR = target frame
        0x30004000,                       # FDRI type1, 0 words (type2 follows)
        0x50000000 | (2 * FRAME_WORDS),   # type2 write 202 words
    ] + frames2 + [
        0x30000001, 0x00000000,           # write CRC reg = 0 (CRC disabled)
        0x30008001, 0x0000000A,           # CMD = GRESTORE
        0x20000000,                       # NOP
        0x30008001, 0x00000005,           # CMD = START
        0x20000000,                       # NOP
        0x30008001, 0x00000007,           # CMD = RCRC
        0x30008001, 0x0000000D,           # CMD = DESYNC
        0x20000000, 0x20000000, 0x20000000, 0x20000000,
    ]

    with open(out, 'w') as f:
        f.write("// auto-generated by icap-build-frame.py -- single-frame ICAP write\n")
        f.write(f"// target frame 0x{FAR_TARGET:08x} (+pad), {len(seq)} words\n")
        f.write(f"#define ICAP_SEQ_LEN {len(seq)}\n")
        f.write("static const uint32_t icap_seq[ICAP_SEQ_LEN] = {\n")
        for i in range(0, len(seq), 6):
            f.write("  " + " ".join(f"0x{x:08x}," for x in seq[i:i+6]) + "\n")
        f.write("};\n")
    print(f"target frame words[{start}:{start+202}], seq = {len(seq)} words -> {out}")
    print(f"frame 0x{FAR_TARGET:08x} word42 = 0x{frames2[42]:08x}")


if __name__ == '__main__':
    main()
