// AUTO-GENERATED by sim/oracle_m753.py — DO NOT EDIT.
// M7.5.3-lite golden: 4-4-2, digits (0, 1), 2x2 pool, seed=3, lr_shift=7, test_acc=0.925
#ifndef M753_VECTORS_H
#define M753_VECTORS_H

#define M7M_FRAC     8
#define M7M_K        2
#define M7M_WSHIFT   2
#define M7M_XSHIFT   2
#define M7M_XSHIFT_H 3
#define M7M_NIN      4
#define M7M_NH       4
#define M7M_NOUT     2
#define M7M_NTEST    40

// biases (Q8.8) — firmware does bias+leaky+requant; weights are in the LUT tile.
static const short M753_B1[4] = { 10,8,-12,-11 };
static const short M753_B2[2] = { 111,136 };

// the two INT8 weight tiles the host ICAP-bakes (L1 pass1, L2 pass2 padded).
static const signed char M753_L1_TILE[4][4] = {
  {3,-3,-3,-2},
  {13,19,21,18},
  {-3,-3,-1,0},
  {1,0,-2,-3}
};
static const signed char M753_L2_TILE[4][4] = {
  {0,27,3,0},
  {14,-14,5,13},
  {0,0,0,0},
  {0,0,0,0}
};

// test set: inputs INT8 (x_q88=v<<XSHIFT), labels, and golden classifications.
static const signed char M753_TEST_X[40][4] = {
  {5,12,12,6},
  {11,18,18,16},
  {2,13,14,2},
  {1,7,6,2},
  {1,6,3,4},
  {6,3,0,7},
  {10,15,15,11},
  {5,8,9,7},
  {1,11,9,3},
  {18,15,15,16},
  {1,11,11,1},
  {11,10,11,13},
  {7,12,12,9},
  {10,9,8,9},
  {4,3,3,6},
  {1,12,12,2},
  {7,6,7,7},
  {7,12,11,10},
  {3,8,6,5},
  {0,11,8,4},
  {9,12,12,10},
  {5,4,4,6},
  {12,11,12,13},
  {10,6,9,9},
  {9,9,10,9},
  {2,6,2,7},
  {0,9,9,2},
  {2,5,1,7},
  {3,3,3,4},
  {3,6,1,9},
  {10,13,12,14},
  {8,14,12,12},
  {1,8,8,2},
  {9,10,10,9},
  {0,6,5,3},
  {1,12,10,3},
  {8,10,9,8},
  {1,10,10,2},
  {13,10,10,13},
  {8,16,16,15}
};
static const unsigned char M753_TEST_Y[40] = { 0,0,1,1,1,1,0,0,1,0,1,0,0,0,1,1,0,0,1,1,0,1,0,0,0,1,1,1,1,1,0,0,1,0,1,1,0,1,0,0 };
static const unsigned char M753_GOLD_CLS[40] = { 0,0,0,1,1,1,0,1,1,0,1,0,0,0,1,1,1,0,1,1,0,1,0,0,0,1,1,1,1,1,0,0,1,0,1,1,0,1,0,0 };

#endif // M753_VECTORS_H
